on: [pull_request, push]

jobs:
  test:
    name: Tests
    # environment: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::898783847255:role/GithubActionsRole
        aws-region: us-west-2
    - name: Who am I?
      run: |
        aws sts get-caller-identity
    - name: And what do I see?
      run: |
        cat README.md
    - name: What about the variables?
      run: |
        echo "The value of S3_BUCKET is '${{ vars.S3_BUCKET }}'"

